# Use the official Go image from the Docker Hub
# FROM golang:1.20-alpine
# docker pull golang:1.22.5
FROM golang:1.22.5
# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Go source code into the container
COPY agent .

# Build the Go app
RUN go build -o main .

# Command to run the executable
CMD ["./main", "--config", "./agent.yml"]
